# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baked', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Email', models.CharField(max_length=264)),
                ('Subject', models.CharField(max_length=264)),
            ],
        ),
    ]
