# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baked', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
