# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baked', '0003_auto_20180517_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='File',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
