# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baked', '0007_auto_20180522_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='registeration',
            name='Email',
            field=models.EmailField(default=0, max_length=264),
            preserve_default=False,
        ),
    ]
